### ISSUE TITLE
Issues identified in README

### ISSUE THREAD

**Issue by cowboyd** [iplaylf2/zephyr#2]
In the project README, you say:

> This is an attempt at structured concurrent programming. However, it seems that Effection 3.0.3 has some issues, causing the project to behave strangely during graceful shutdown. I’m considering whether to abandon it.

Would love to know what these issues are and if we can address them.

**Comment by iplaylf2** [comment]
@cowboyd Thank you for your visit. 
Actually, the issue was with my code logic, which I've resolved. Now, I'm happily continuing to explore Effection on the `feat/ongong-work` branch!
 I apologize for my moment of frustration reflected in the README. I will update the README once my project reaches the next completion stage.

**Comment by cowboyd** [comment]
@iplaylf2 sounds great! Keep us posted, and please feel welcome to drop in to share any questions or future frustrations with us on either GitHub or Discord...
